modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "Rarin"
description = "*"
logoFile="logo.png"

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory
versionRange = "${neo_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId="create"
type="required"
versionRange="[6.0.9,6.1.0)"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="create_connected"
type="required"
versionRange="[1.2.0-mc1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="createcasing"
type="required"
versionRange="[1.7.1-fix2,)"
ordering="NONE"
side="BOTH"